version: '3.7'

services:

  hot-reload:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      # used to not to mount directory /app/node_modules in container (it's provided by install in image)
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
